### PR TITLE
Revert changes to fix CI

### PR DESCRIPTION
**Pull request by m-mohr**
Reverting the recent CI breaking changes for now to unblock other PRs.

The changes that we revert here are preserved via #220

### CODE REVIEW

**Review by tschaub — APPROVED** [review]

**Review by cholmes — APPROVED** [review]
Thanks for reverting this. Let's at least get in the notification that it's a draft spec in soon - I'll make a PR for that. And I'll work on a PR to get this back in to the repo, but not breaking the build and confusing people with the readme template.

**Comment by cholmes** [comment]
> And I'll work on a PR to get this back in to the repo, 

And of course @m-mohr already has a PR ready at https://github.com/opengeospatial/geoparquet/pull/220 :) Thanks!

**Comment by m-mohr** [comment]
Not quite, #220 is the full set of changes from Gobe. We should probably cherry pick the Markdown changes that add the note from there. Can do it later...

**Comment by m-mohr** [comment]
... Or we just use #205

**Pull request merged**
