### PR TITLE
Update scripts dependencies

### PR DESCRIPTION
**Pull request by kylebarron**
Closes https://github.com/opengeospatial/geoparquet/issues/178

Now 

```
poetry install
poetry run python generate_example.py
```

works on my machine

### CODE REVIEW

**Comment by kylebarron** [comment]
This fails the tests because it uses a later version of GeoPandas/Pyproj and writes PROJJSON with a schema of `v0.6`. I created https://github.com/opengeospatial/geoparquet/issues/180

**Comment by tschaub** [comment]
This should probably be a dedicated ticket, but I've run into this same problem that [the CI job is hitting](https://github.com/opengeospatial/geoparquet/actions/runs/5685503475/job/15410506979?pr=179) with the projjson schema dependency.  It is not a real problem until a version of projjson is released that is incompatible with https://proj.org/schemas/v0.5/projjson.schema.json.  But it looks like we need to relax the `test_json_schema.py` so it isn't as strict about the version that is included in the generated projjson.

**Comment by kylebarron** [comment]
> But it looks like we need to relax the `test_json_schema.py` so it isn't as strict about the version that is included in the generated projjson.

It looks like pytest actually succeeds (you can run `poetry run python generate_example.py && poetry run pytest` locally; it works for me). It's these lines in the CI:

https://github.com/opengeospatial/geoparquet/blob/ad32ccaf5534a3680e62bf9de3f9837befd9c717/.github/workflows/scripts.yml#L57-L61

**Comment by tschaub** [comment]
Just saw the same after re-reading.  Yes, `test -z "$(git status --porcelain)"` is the problem.

**Review by tschaub — APPROVED** [review]

**Comment by tschaub** [comment]
Woohoo.  Thanks, @kylebarron

**Comment by tschaub** [comment]
I'll merge this so we can proceed with the re-release.  Hope that sounds ok.  Thanks for fixing it up.

**Pull request merged**
